version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=fede
      - POSTGRES_PASSWORD=admin2144
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin2144
    ports:
      - 5050:80
